### ISSUE TITLE
What is this `iso-marketing` app icon?

### ISSUE THREAD

**Issue by stuffmc** [br1sk/brisk-ios#28]
I know it would be the 1024p version for iTunes but it's just in the .json file, not even an actual filename.

I'd go and delete and do a Pull Request, but I prefer to ask first.

What annoys me is that it shows up as a Warning.

Also, is the app only supported on iOS 11 (which would be okay, I'm just asking).

**Comment by florianbuerger** [comment]
This comes from Xcode 9 which includes the iOS 11 marketing image (1024pt). I use Xcode 9 as a daily driver and there is no warning. 

If it bothers you that much, go ahed and delete it 😉 

The app works fine on iOS 10.

**Comment by stuffmc** [comment]
Ah, that's interesting. You can close this Issue then.
